### ISSUE TITLE
Regression in OpenJFX dependency detection and installation

### ISSUE THREAD

**Issue by jafarlihi** [Col-E/Recaf#156]
**Describe the bug**

Two regressions:
1) OpenJFX presence detection at Recaf startup has stopped working since version 1.15.4. This works fine in 1.15.3.
2) 1.15.3 fails to download the OpenJFX automatically. This works fine in version 1.15.2.

**To Reproduce**
I'm running Arch Linux x86_64, "jdk11-openjdk" package.

**1.15.5:**
`> java -jar recaf-1.15.5.jar`
`[WARN:7/9/19, 9:41 PM] Recaf cannot acquire the classpath for bootstrap classes when running in Java 9 or above. This will affect auto-complete suggestions in Assembler!
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/value/ObservableValue
	at me.coley.recaf.Logging.log(Logging.java:239)
	at me.coley.recaf.Logging.warn(Logging.java:121)
	at me.coley.recaf.util.Classpath$ClassPathScanner.scan(Classpath.java:171)
	at me.coley.recaf.util.Classpath.<clinit>(Classpath.java:40)
	at me.coley.recaf.util.Dependencies.exists(Dependencies.java:88)
	at me.coley.recaf.util.Dependencies.checkJFX(Dependencies.java:62)
	at me.coley.recaf.util.Dependencies.check(Dependencies.java:47)
	at me.coley.recaf.Recaf.main(Recaf.java:13)
Caused by: java.lang.ClassNotFoundException: javafx.beans.value.ObservableValue
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more
`

**1.15.4**
`> java -jar recaf-1.15.4.jar`
`[WARN:7/9/19, 9:49 PM] Recaf cannot acquire the classpath for bootstrap classes when running in Java 9 or above. This will affect auto-complete suggestions in Assembler!
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/value/ObservableValue
	at me.coley.recaf.Logging.log(Logging.java:239)
	at me.coley.recaf.Logging.warn(Logging.java:121)
	at me.coley.recaf.util.Classpath$ClassPathScanner.scan(Classpath.java:171)
	at me.coley.recaf.util.Classpath.<clinit>(Classpath.java:40)
	at me.coley.recaf.util.Dependencies.exists(Dependencies.java:88)
	at me.coley.recaf.util.Dependencies.checkJFX(Dependencies.java:62)
	at me.coley.recaf.util.Dependencies.check(Dependencies.java:47)
	at me.coley.recaf.Recaf.main(Recaf.java:13)
Caused by: java.lang.ClassNotFoundException: javafx.beans.value.ObservableValue
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more
`

**1.15.3 (doesn't actually download the dependencies or rerun, exits immediately after printing)**
`> java -jar recaf-1.15.3.jar`
`Detected JDK 11+ without OpenJFX dependencies
Dependencies will be downloaded and Recaf will restart...
Rerunning
`

**1.15.2 (downloads the dependencies and reruns successfully)**
`> java -jar recaf-1.15.2.jar`
`Detected JDK 11+ without OpenJFX dependencies
Dependencies will be downloaded and Recaf will restart...
Rerunning
`

Additionally 1.15.4/1.15.5/1.15.4 still keeps outputting the same thing even after 1.15.2 fetches the dependencies and reruns successfully.

**Comment by jafarlihi** [comment]
The first regression is probably introduced in the PR #136

**Comment by andylizi** [comment]
:sigh: Another classloading related problem...  Investigating.

**Comment by andylizi** [comment]
By the way, 
```
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/beans/value/ObservableValue
        at me.coley.recaf.Logging.log(Logging.java:239)
        at me.coley.recaf.Logging.warn(Logging.java:121)
        at me.coley.recaf.util.Classpath$ClassPathScanner.scan(Classpath.java:171)
        at me.coley.recaf.util.Classpath.<clinit>(Classpath.java:40)
        at me.coley.recaf.util.Dependencies.exists(Dependencies.java:88)
        at me.coley.recaf.util.Dependencies.checkJFX(Dependencies.java:62)
        at me.coley.recaf.util.Dependencies.check(Dependencies.java:47)
        at me.coley.recaf.Recaf.main(Recaf.java:24)
Caused by: java.lang.ClassNotFoundException: javafx.beans.value.ObservableValue
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 8 more
```

https://github.com/Col-E/Recaf/blob/722a45072646722f69eab90839b019dd4dd974e6/src/main/java/me/coley/recaf/Logging.java#L239-L241

When JavaFX is not included in classpath, `JavaFX.isToolkitLoaded()` will throw an `ClassNotFoundException` instead of return `false`.
